theme: bootstrap-theme
site-name: test-site
site-url: https://www.example.com
public: public
copyright: Copyright pybooksite 2022
favicon: /img/favicon.ico
menu:
  Home: /
  About: /about/
  Blog: /blog/
googleanalytics: XXXXXXX-GA
googleadsense: ca-pub-XXXX
googleadsenseslot: XXXX
mathjax: true
social:
  Twitter: twitter.com
  Github: github.com
__top: top1.html
__bottom: bottom1.html
__side: side1.html