theme: html-theme
site-name: test-site
site-url: https://www.example.com
copyright: Copyright pybooksite 2022
menu:
  Home: /
  About: /about/
  Books: /books/
googleanalytics: XXXXXXX-GA
mathjax: true
social:
  Twitter: twitter.com
  Github: github.com