theme: html-theme
site-name: test-site
site-url: https://www.example.com
public: public
copyright: Copyright pybooksite 2022
menu:
  Home: /
  About: /about/
  Blog: /blog/
googleanalytics: XXXXXXX-GA
googleadsense: ca-pub-XXXX
googleadsenseslot: XXXX
mathjax: true
social:
  Twitter: twitter.com
  Github: github.com
__advert: ad2.html